services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_FEATURES=admin-fine-grained-authz,authorization,login,client-policies,persistent-user-sessions
    ports:
      - "8080:8080"

  pgadmin:
    scale: 0
