name: Build
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Start backend with Docker Compose
        working-directory: ./backend
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

      - name: Wait for backend to be ready
        run: |
          until curl -s http://localhost:3000/health/liveness | grep -q '"status":"ok"'; do
            echo "Waiting for backend to be ready..."
            sleep 5
          done

      # Optional: If you want to run Angular inside Docker Compose, uncomment the next section
      # - name: Start Angular frontend with Docker Compose
      #   working-directory: ./angular-buch-frontend
      #   run: docker-compose up -d

      - name: Start Angular (if not using Docker)
        working-directory: ./angular-buch-frontend
        run: npm install && npm run start & # Run in background

      - name: Wait for Angular to be ready
        run: |
          until curl -s http://localhost:4200 | grep -q "<title>Angular"; do
            echo "Waiting for Angular app to be ready..."
            sleep 5
          done

      - name: Run Cypress Tests
        working-directory: ./angular-buch-frontend
        run: npx cypress run --spec "cypress/e2e/backend-health.spec.js"

      - name: Run Angular Tests
        working-directory: ./angular-buch-frontend
        run: npm run test -- --watch=false
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}